# Generated by Django 2.2.23 on 2021-05-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210525_2108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.AddField(
            model_name='book',
            name='rent',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cd',
            name='rent',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='rent',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.PositiveIntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cd',
            name='time',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='cd',
            name='tracks',
            field=models.PositiveSmallIntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='film',
            name='time',
            field=models.PositiveSmallIntegerField(max_length=3),
        ),
    ]
